### PR TITLE
Mothball the project

### PR DESCRIPTION
**Pull request by cole-miller**
Signed-off-by: Cole Miller <cole.miller@canonical.com>

### CODE REVIEW

**Comment by freeekanayaka** [comment]
Hey Cole, not really related to this PR, but I've noticed that issues have now been disabled for this repository. I assume the goal would be to avoid having people file new issues.

However, I think continuing to be able to access the existing issues would be valuable, since they contain discussions and considerations that might be relevant when understanding current code. Some of those issues are also referenced in the open issues that I see have been transferred to canonical/dqlite, and they contain additional information that is probably going to be useful when tackling them.

Since the rate of new issues opened by third parties is low, would it be possible to re-enable the issues section so that the old content is back online?

**Comment by cole-miller** [comment]
Unfortunately just re-opening issues on this repository won't recover the issues that were transferred to canonical/dqlite. GitHub doesn't offer a way to nondestructively copy issues to another repository, and I wanted those issues to be present in canonical/dqlite since they're by and large still relevant to dqlite, so I transferred them there.

What do you think of the idea of adding a link to the canonical/raft README that points to https://github.com/canonical/dqlite/issues?q=is%3Aissue+label%3Atransferred-from-raft? That will list all the issues that were extant in canonical/raft just before I did the transfer.

**Comment by cole-miller** [comment]
I've reopened issues for now so that everyone can browse the closed issues on this repository. The issues that I closed yesterday without transferring to canonical/dqlite are:

- https://github.com/canonical/raft/issues/430
- https://github.com/canonical/raft/issues/475
- https://github.com/canonical/raft/issues/230

**Comment by freeekanayaka** [comment]
> Unfortunately just re-opening issues on this repository won't recover the issues that were transferred to canonical/dqlite. GitHub doesn't offer a way to nondestructively copy issues to another repository, and I wanted those issues to be present in canonical/dqlite since they're by and large still relevant to dqlite, so I transferred them there.
> 
> What do you think of the idea of adding a link to the canonical/raft README that points to https://github.com/canonical/dqlite/issues?q=is%3Aissue+label%3Atransferred-from-raft? That will list all the issues that were extant in canonical/raft just before I did the transfer.

I guess I didn't articulate this well. The issues that have been transferred are fine, since they have the same content and can be found in one way or another.

The problem I see is for the issues that were kept in this repository and are now not available anymore. For example: if one looks at some existing code and wants to see background discussions that led to it, now that can't be done anymore.

I'd suggest to just re-activate the Issues tab of this repository, which as far as I can see only has the downside of letting people post new content. But that should be rather rare and not a big deal.

**Comment by cole-miller** [comment]
> I guess I didn't articulate this well.

No, it's my bad, I wasn't thinking about closed issues at all. You're right that it makes more sense to keep the issues open for that reason.

**Review by MathieuBordere — APPROVED** [review]

**Pull request merged**
