### PR TITLE
raft.h: Introduce raft_tracer_v2 for more flexible tracing

### PR DESCRIPTION
**Pull request by cole-miller**
Here is a stab at introducing a more flexible tracing scheme for raft, that should hopefully support our plans to revamp and integrate tracing across raft and dqlite. It is backwards-compatible.

Signed-off-by: Cole Miller <cole.miller@canonical.com>

### CODE REVIEW

**Comment by MathieuBordere** [comment]
> > `Error: test/lib/heap.c:138: memory leak: -1 outstanding allocations`
> 
> That's weird, maybe something to do with #397?



> > `Error: test/lib/heap.c:138: memory leak: -1 outstanding allocations`
> 
> That's weird, maybe something to do with #397?

Probably, the leak detection is pretty basic. The original code checked if there are the same number of `alloc` and `free` calls, #397 violates that assumption. We could revert #397 and then check that we don't do 0-size allocations.

**Comment by MathieuBordere** [comment]
Looks okay, before merging this it probably makes senseif we directly start handling the new tracer version in the tracing code?

**Comment by freeekanayaka** [comment]
I'd like to have a broader picture of the use cases and requirements, so we make sure we are not missing something. For example, the point @cole-miller makes about metrics seems important: if we decide that tracing and metrics should share tooling, then it'd be good to have an idea of what will be needed and if any accommodation is due (my gut feeling is that metrics is something separate that won't share tooling, but I didn't quite reason on it).

**Comment by freeekanayaka** [comment]
> > > `Error: test/lib/heap.c:138: memory leak: -1 outstanding allocations`
> > 
> > 
> > That's weird, maybe something to do with #397?
> 
> > > `Error: test/lib/heap.c:138: memory leak: -1 outstanding allocations`
> > 
> > 
> > That's weird, maybe something to do with #397?
> 
> Probably, the leak detection is pretty basic. The original code checked if there are the same number of `alloc` and `free` calls, #397 violates that assumption. We could revert #397 and then check that we don't do 0-size allocations.

Yes, that leak detection is mainly a sanity check for what I'd say should be the good practice of performing only greater-than-zero allocations and releasing the one and only times. The 0-size allocations might save a line or two of code in some cases, but I'm not sure it's worth, since it's quite handy to know that allocations and deallocations are balanced, as a first data point before further debugging a memory leak. To further debug a memory leak triggered during the test suite then the `--enable-sanitize` configure option is what should be used at the moment.

**Pull request closed without merging**
